### ISSUE TITLE
password

### ISSUE THREAD

**Issue by BrittBratt5162** [Uniswap/universe#10]
I need help with uniswap. when I try to transfer over my password isn't right and I tried all of them. how to i get my money from my wallets if I cant retrieve my password. Its saying they are wrong. and I don't remember setting one up. what can I do??

**Comment by jumptoka** [comment]
Hallo zusammen
Das Problem hab ich auch, vielleicht das gleiche: Ich habe einen Ether überwiesen (wollte bei shopping.io den Token SPI kaufen) auf eine Etheradresse, die in shopping.io angezeigt wurde und dann bei Uniswap auch. Als ich den Ether in SPI tauschen wollte, kam dieses Fenster mit dem Google-Confirm und fragte nach einem Passwort! Keine Ahnung, welches er wollte, ich gab auf alle Fälle die falschen ein, er brach dann ab.
Irgendwann lud er die Seite neu und ab da war die Etheradresse auch weg
Nun find ich natürlich meinen Ether nicht mehr :(
