### ISSUE TITLE
Regarding the Website / DNS

### ISSUE THREAD

**Issue by michael-spengler** [Uniswap/universe#12]
Hi Uniswap Team.

I appreciate Uniswap very much and I would like to offer a proposal.

Would it make sense to use one of the following options? 

1. https://unstoppabledomains.com/
2. https://ens.domains/

or perhaps even both options :)

I'd like to ensure that Uniswap is about to stay.

Thanks for checking this
Michael

**Comment by NoahZinsmeister** [comment]
see https://uniswap.org/blog/ipfs-uniswap-interface/
