### ISSUE TITLE
The discord link appears to be broken

### ISSUE THREAD

**Issue by privateidentity** [Uniswap/universe#7]
Hi,

The discord link appears to be broken.
https://discord.com/invite/tX9NDcK
Is it possible to get a new working link to replace the old one.

Also the twitter link directs to a suspended account.
https://twitter.com/UniswapExchange
Maybe changing it to link to this twitter account would be better.
https://twitter.com/uniswapprotocol

Thanks

**Comment by dahifi** [comment]
Pull request submitted.
